train: [0]
test: [1]
plot: [0]
load: [1]

model: [Wong2020Fast]
model_norm: "Linf"
dataset: [cifar10c]
corruptions: [["shot_noise", "pixelate", "gaussian_noise", "impulse_noise", "glass_blur", "jpeg_compression", "snow", "motion_blur", "defocus_blur",
              "brightness", "fog", "zoom_blur", "frost", "contrast", "elastic_transform"], ["shot_noise"],  ["pixelate"], ["gaussian_noise"], ["impulse_noise"],
              ["glass_blur"], ["jpeg_compression"], ["snow"], ["motion_blur"], ["defocus_blur"], ["brightness"], ["fog"], ["zoom_blur"], ["frost"],
              ["contrast"], ["elastic_transform"]]
severity: 5

pretrained: [True]
epochs: [10]
lr: [0.1]
lr_schedule: [step_wise]
optimizer: [sgdm]
counterattack_defense: [
          {'iters_start':20, 'counter_type':"max_loss",'iters_counter':20, 'step_size':2/255, 'step_size_counter':2/255, 'epsilon_start':16/255,
           'epsilon_counter':8/255, 'norm':"linf", 'eot_iters':0, 'eot_magnitude':0},
          {'iters_start':20, 'counter_type':"max_loss",'iters_counter':20, 'step_size':0.125, 'step_size_counter':0.125, 'epsilon_start':1,
           'epsilon_counter':0.5, 'norm':"l2", 'eot_iters':0, 'eot_magnitude':0},
]


attacks: [[
          {"type":normal, "key":"accuracy"},
          ]]

result_path: Results_ICML

training_type: [normal]
loss_function: [sce]
augmentation: [[]]
seed: [0]
batch_size: [100]