train: [0]
test: [1]
plot: [0]
load: [1]

model: [Wong2020Fast]
model_norm: "Linf"
dataset: [cifar10]

pretrained: [True]
epochs: [10]
lr: [0.1]
lr_schedule: [step_wise]
optimizer: [sgdm]
counterattack_defense: [
          {'iters_start':20, 'counter_type':"max_loss",'iters_counter':20, 'step_size':2/255, 'step_size_counter':2/255, 'epsilon_start':16/255,
           'epsilon_counter':8/255, 'norm':"linf", 'eot_iters':0, 'eot_magnitude':0},
          {'iters_start':20, 'counter_type':"max_loss",'iters_counter':20, 'step_size':0.125, 'step_size_counter':0.125, 'epsilon_start':1,
           'epsilon_counter':0.5, 'norm':"l2", 'eot_iters':0, 'eot_magnitude':0},
]

attacks: [[
          {"type":translation, "key":"translation_accuracy", "translation":5},
          {"type":rotation, "key":"rotation_accuracy", "rotation":20},
          {"type":fab, "key":"fab_accuracy", "iters":100, "norm": linf},
          {"type":square, "key":"square_accuracy", "iters":5000, "norm": linf},
          {"type":apgd, "key":"apgd_accuracy", "iters":100, "restarts":1, "norm": linf, "loss":"ce"},
          {"type":pgd, "key":"pgd_accuracy", "iters":100, "restarts":1, "norm": linf, "early_stopping":False,
           "EOT_type":"Noise", "EOT_eps_factor":1, "loss":"ce"},
          {"type":pgd, "key":"pgd_accuracy", "iters":100, "restarts":1, "norm": linf, "early_stopping":False,
           "EOT_iters":4, "EOT_type":"Attack", "EOT_attack_iters":4, "EOT_eps_factor":1, "loss":"ce"},
          {"type":apgd, "key":"apgd_accuracy", "iters":100, "restarts":1, "norm": linf, "loss":"dlr"},
          ]]

test_size: 1
result_path: Results_ICML

training_type: [normal]
loss_function: [sce]
augmentation: [[]]
seed: [0]
batch_size: [100]